# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71c52742e10fc98dd45c2d680a981092073cb838bf1fa5762c113efa5d529bf99eba7d7c53928dd6e72ea64dbebac0cb2e52f122044c3cff9e4ddc857e6f067b

test:
  secret_key_base: e068a04e65717c29f44648f9d6ac2e179b0491bd15c1f2ae4775f5165fbed2394eb1f67171a8dee3577168d1f4ec228eaef7942260058d11ac2e07058bc4bfab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
